version: "3"

services:
  # アプリケーション
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/go/src/github.com/nw-union/hidel-wiki:cached
      # --- exclude volums ---
      - /go/src/github.com/nw-union/hidel-wiki/.docker/
    ports:
      - 8080:8080
    depends_on:
      - es

  # ElasticSearch (データベース)
  es:
    build: .docker/es
    environment:
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./.docker/es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
