FROM golang:latest

ENV GOOS=linux
ENV GO111MODULE=on

WORKDIR /development_tool
RUN go mod init development_tool && \
	go get -u github.com/oxequa/realize && \
	rm -rf /go/pkg

WORKDIR $GOPATH/src/github.com/nw-union/hidel-wiki
EXPOSE 8080

# あらかじめpkgを取得しておいて、起動時間を減らす
COPY . .
RUN go mod download

CMD realize start
